name: Deploy
on:
  release:
      types: [ published, prereleased ]
jobs:
  build:
    name: Create And Upload Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@master

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Use 7cav mission builder
        uses: ColdEvul/action-build-mission@develop
        with:
          missions-dir: Maps/
          version-tag: ${{ steps.get_version.outputs.VERSION }}

      - name: Upload Release
        uses: JasonEtco/upload-to-release@master
        with:
          args: release/7Cav_RHS_InvadeAndAnnex_${{ steps.get_version.outputs.VERSION }}.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
