name: Deploy
on:
  release:
      types: [ published, prereleased ]
jobs:
  build:
    name: Create And Upload Release
    runs-on: ubuntu-latest
    steps:

      - name: Setup env
        run: |
          apt-get update
          apt-get install gcc pkg-config libssl-dev -y

      - name: Checkout code
        uses: actions/checkout@master

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Checkout armake2
        uses: actions/checkout@master
        with:
          repository: KoffeinFlummi/armake2
          path: ./armake2

      # setup cargo for building armake2 (rust)
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable          

      - name: Build armake2
        run: |
          cd ./armake2
          cargo build --release
          mv target/release/armake2 /usr/bin/armake2
          cd ../

      - name: Build release
        run: ./tools/deploy.sh ${{ steps.get_version.outputs.VERSION }}

      - name: Upload Release
        uses: JasonEtco/upload-to-release@master
        with:
          args: release/*.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}